### PR TITLE
Follow up on namespace change

### PR DESCRIPTION
**Pull request by gpummer**
'som' script had the old namespace, so I changed this to the new namespace 'trufflesom.vm.Universe'.
I also integrated the proposed test from @smarr  calling the som script.

This is my first pull request to TruffleSOM. Any tips are appreciated. Maybe I should have made 3 PRs?

### CODE REVIEW

**Comment by smarr** [comment]
Hi @gpummer, thanks a lot for the PR!

One PR is perfectly fine.
Will look at it at some point today hopefully, but am currently traveling, so, may take some time.

**Comment by smarr** [comment]
Sorry, guess, that's not exactly "today" that I managed to look at it.

I did some minor polish:
 - turn tabs into spaces in the `build.xml` to fit with the rest of the file
 - and use the `tests` target on Travis to actually run the tests :)

**Comment by smarr** [comment]
And after running the tests on Travis, which failed, I added the `-G` flag to avoid needing Graal on Travis.
Now it's all good, and I'll merge it.

Thanks a lot for the PR!

BTW, what brought you to SOM?

**Comment by gpummer** [comment]
Hello!

Cool! Sorry for the tabs, I will change my eclipse settings to spaces. I did multiple tests, but somehow travis is a little bit different (a missing -G was never a problem). Hmm, maybe I have to set up travis my self.

I found SOM by accident (well, Google :)), searching for a Smalltalk 'dialect' running on a JVM. Somehow I immediately felt in love with your repos (sorry). Actively maintained, super clean code, helpful documentation, working tests. And TruffleSOM is fast too. I managed to implement some primitives to communicate between SOM and Java in a few hours. And I'm learning so many new things with SOM. Like gradle :) (My 'build.gradle' is not ready for release, because I have troubles with the annotation processors). To keep a long story short: I like SOM:)

**Comment by smarr** [comment]
Nice to hear :)

Bye the way, we were thinking of moving to Gradle too, possibly for SOMns first: https://github.com/smarr/SOMns/issues/272

Would also consider it for SOM/TruffleSOM if you got it work :)

**Comment by gpummer** [comment]
I will try my best. Weekend is coming.

**Pull request merged**
