### PR TITLE
Move to JDK17

### PR DESCRIPTION
**Pull request by smarr**
This PR drops support for JDK8 from TruffleSOM, and moves us all the way to JDK17.

Thanks @fniephaus for the initial bits for the module support!

@OctaveLarose, I'll merge this only after verifying that performance is ok, but there seem to be some issues. Please see whether this works for you.

In addition to the JDK changes, this has also a fix for flag semantics for the launcher:
  * `-LG`: now really means that we don't use the libgraal/libjvmcompile static library
  * `-EG`: now really means that we do not use the embedded Graal (in ./libs/jvmci, and is orthogonal to `-LG`)
  * `-G` now implies `-EG`

### CODE REVIEW

**Comment by smarr** [comment]
At least one of the performance issues was caused by compiler issues around frame accesses, regressions that got introduces with the new truffle frame.
This one should be fixed with the last commit that updates Truffle+Graal to the version of today.

**Comment by smarr** [comment]
Hmpf. Performance regresses on various bits. Needs more investigation before this can be merged: https://rebench.stefan-marr.de/compare/TruffleSOM/b06d08c5840eeda122d62af226d8a29d38478f95/c71c4a48a03b6dd91d418b968afbad5040cbd11c

**Comment by fniephaus** [comment]
I remember some slowdowns migrating TruffleSqueak from JDK8 a while ago and couldn't really figure out why. After some fruitless digging, I blamed G1 GC, the new default GC, for at least some of the slowdowns and moved on.

**Comment by smarr** [comment]
TruffleSafepoints are the main culprit for the micro benchmarks.
Though, the GraphSearch one still doesn't make sense to me.

**Comment by fniephaus** [comment]
TruffleSafepoints didn't exist when we migrated. It's unfortunate that these cause noticeable overhead for the micro benchmarks but at least you can explain the slowdowns.

**Comment by smarr** [comment]
Oh my, these benchmarks hate G1: https://rebench.stefan-marr.de/compare/TruffleSOM/b06d08c5840eeda122d62af226d8a29d38478f95/e43b9f146923bd5da7f206f1a7c05dcfe9e75a1a

**Comment by fniephaus** [comment]
I told you! :)

**Comment by smarr** [comment]
Performance results with TruffleSafepoints disabled, and `-XX:+UseParallelGC`: https://rebench.stefan-marr.de/compare/TruffleSOM/b06d08c5840eeda122d62af226d8a29d38478f95/f57c56442c76816776d0175c614cf224b641fb15

For the interpreters, it's still not great.
On the AST interpreter, regressions are within something like 4-10%. On the bytecode interpreter, it's more like 7-10%, with larger outliers.
On EE, regressions are bigger, probably because my hacks don't apply.
Peak performance has improved on a few benchmarks.

**Comment by smarr** [comment]
#### Isolating the cost of the TruffleSafepoints
Report run to indicate cost of enabling them: https://rebench.stefan-marr.de/compare/TruffleSOM/e1407636fe788e092d3a23e4b7f9fb888225151f/173feecbd55fab5e322502a0c207eb90eb7db167

SomSom is unchanged, good.
DeltaBlue and GraphSearch see some overhead, but seems very noisy.
The losers are the really tight microbenchmarks like Sum, Sieve, and WhileLoop.
Possibly Storage.

Overall, seems not worth the hassle of patching them out.

**Comment by smarr** [comment]
@eregon this still uses the `FrameSlot` API. My experiments with the new API are on another branch, but pretty old (30 merged PRs behind).

**Comment by smarr** [comment]
https://rebench.stefan-marr.de/compare/TruffleSOM/eaf477afd7612d3af4cab04447afd1df2ffbd3df/418c69bdc3006020ca3b483c4f806ba4ca23c629

**Pull request merged**
